CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;
CREATE TABLE IF NOT EXISTS compteur (
    id INT AUTO_INCREMENT PRIMARY KEY,
    valeur INT NOT NULL,
    temps TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO compteur (valeur) VALUES (0);
